#!/bin/bash

for i in  {0..100}
do	
	echo -e "\n\nconnection # $i\n\n"
	echo "Q" | ./openssl s_client -connect 192.168.0.113:44330 -cert ../../Desktop/openssl-3.0/apps/my_keys/client_certificate.pem -key ../../Desktop/openssl-3.0/apps/my_keys/client_cert_pkey.pem -did_methods ott,eth 2> stderr.txt | grep "Total time" | cut -d " " -f 4 >> c_cert_didm_times 
done
