#!/bin/bash

HOST=localhost
DID=43FAB3D59E0FB5611622CC24E3ECD659D249622333F66C7AAF32E9A958367992

for i in  {0..100}
do	
	echo -e "\n\nconnection # $i\n\n"
	echo "Q" | ../openssl s_client -connect $HOST:44330 -did did:ott:$DID 2> stderr.txt | grep "Total time" | cut -d " " -f 4 >> cross-auth-client-did-times 
done
