#!/bin/bash

if [ $# -ne 3 ]; then
	echo "USAGE: $0 [HOST] [PORT] [KEY_TYPE]"
	exit 0
fi

HOST=$1
PORT=$2
DID=$(cat my_keys/devnet/$3/client_did)
DID_PKEY=my_keys/devnet/$3/client_did_pkey.pem 

for i in  {0..100}
do	
	echo -e "\n\nconnection # $i\n\n"
	echo "Q" | ../openssl s_client -connect $HOST:$PORT -did $DID 2> stderr.txt | grep "Total time" | cut -d " " -f 4 >> $0-times 
done
