#!/bin/bash

if [ $# -ne 2 ]; then
	echo "USAGE: $0 [HOST] [PORT]"
	exit 0
fi

HOST=$1
PORT=$2
CERT=my_keys/client_certificate.pem
CERT_PKEY=my_keys/client_cert_pkey.pem

for i in  {0..100}
do	
	echo -e "\n\nconnection # $i\n\n"
	echo "Q" | ../openssl s_client -connect $HOST:$PORT -cert $CERT -key $CERT_PKEY -did_methods ott,eth 2> stderr.txt | grep "Total time" | cut -d " " -f 4 >> $0-times 
done
