#!/bin/bash

HOST=localhost
DID=AC6B7063F10363A48E07216DACAE820EC87B740B8CCCEBC5E5A45547DD4AEC74 

for i in  {0..100}
do	
	echo -e "\n\nconnection # $i\n\n"
	echo "Q" | ../openssl s_client -connect $HOST:44330 -did did:ott:$DID -did_methods ott,eth 2> stderr.txt | grep "Total time" | cut -d " " -f 4 >> mutual-did-auth-times 
done
