#!/bin/bash

for i in  {0..100}
do	
	echo -e "\n\nconnection # $i\n\n"
	echo "Q" | ./openssl s_client -connect 192.168.0.120:44330 2> stderr.txt | grep "Total time" | cut -d " " -f 4 >> c_noauth_cert_times
done
