#!/bin/bash

if [ $# -ne 2 ]; then
	echo "USAGE: $0 [HOST] [PORT]"
	exit 0
fi

HOST=$1
PORT=$2

for i in  {0..100}
do	
	echo -e "\n\nconnection # $i\n\n"
	echo "Q" | ../openssl s_client -connect $HOST:$PORT 2> stderr.txt | grep "Total time" | cut -d " " -f 4 >> $0-times
done
