#!/bin/bash

SERVER_CERT=my_keys/server_certificate.pem
SERVER_PRIV_KEY=my_keys/server_cert_pkey.pem

../openssl s_server -accept 44330 -www -verify 1 -cert $SERVER_CERT -key $SERVER_PRIV_KEY -did_methods ott,eth
