#!/bin/bash

if [ $# -ne 2 ]; then
	echo "USAGE: $0 [PORT] [KEY_TYPE]"
	exit 0
fi

PORT=$1
DID=$(cat my_keys/devnet/$2/server_did)
DID_PKEY=my_keys/devnet/$2/server_did_pkey.pem

../openssl s_server -accept $PORT -www -nocert -verify 1 -did $DID -key $DID_PKEY 2>> times
