#!/bin/bash

if [ $# -ne 1 ]; then
	echo "USAGE: $0 [PORT]"
	exit 0
fi

PORT=$1
CERT=my_keys/server_certificate.pem
CERT_PKEY=my_keys/server_cert_pkey.pem

../openssl s_server -accept $PORT -www -verify 1 -cert $CERT -key $CERT_PKEY -did_methods ott,eth
