#!/bin/bash

SERVER_CERT=my_keys/server_certificate.pem
SERVER_PRIV_KEY=my_keys/server_cert_pkey.pem

../openssl s_server -cert $SERVER_CERT -key $SERVER_PRIV_KEY -accept 44330 -verify 1 -www 2>> times

