#!/bin/bash

if [ $# -ne 2 ]; then
	echo "USAGE: $0 [PORT] [KEY_TYPE]"
	exit 0
fi

PORT=$1
DID=$(cat my_keys/devnet/$2/server_did)

../openssl s_server -accept $1 -www -nocert -did $DID -did_methods ott,eth
